layout_spectrum: 0.7150537
typography_spectrum: 0.8942652
color:
  saturation: 0.172043
  lightness: 0.2329749
  brandStrength: 0.827957
  brandColors:
    - '#FFFFFF'
    - '#543831'
    - '#5D5C5B'
    - '#916C67'
    - '#CFD0CE'
  rhythmicContrast: 0.7383512
name: paulrobinson
