name: paulrobinson
favicon: null
layout_spectrum: 0.50051
typography_spectrum: 0.85613
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#262230'
    - '#dec098'
    - '#6a3936'
    - '#be9b7a'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
